CICD On my way

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -28,45 +28,26 @@ jobs:
       - name: Copy JAR to GCP VM
         uses: appleboy/scp-action@v0.1.4
         with:
-            host: ${{ secrets.VM_HOST }}
-            username: ${{ secrets.VM_USER }}
-            key: ${{ secrets.SSH_PRIVATE_KEY }}
-            source: "target/*.jar"
-            target: "/home/${{ secrets.VM_USER }}/Goceng-prod"
+          host: ${{ secrets.VM_HOST }}
+          username: ${{ secrets.VM_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: "target/*.jar"
+          target: "/home/${{ secrets.VM_USER }}/Goceng-prod"
 
       - name: Run Spring Boot on Ubuntu VM with Env Vars
         uses: appleboy/ssh-action@v0.1.7
         with:
-            host: ${{ secrets.VM_HOST }}
-            username: ${{ secrets.VM_USER }}
-            key: ${{ secrets.SSH_PRIVATE_KEY }}
-            envs: DB_URL,DB_USER,DB_PASS
-            script: |
-              export DB_URL=${{ secrets.DB_URL }}
-              export DB_USER=${{ secrets.DB_USER }}
-              export DB_PASS=${{ secrets.DB_PASS }}
-              
-              pkill -f 'java' || true
-              cd /home/${{ secrets.VM_USER }}/Goceng-prod/target
-              nohup java -jar *.jar --spring.profiles.active=prod > app.log 2>&1 &
-
-#      - name: Copy JAR to Ubuntu VM
-#        uses: appleboy/scp-action@v0.1.4
-#        with:
-#          host: ${{ secrets.SSH_HOST }}
-#          username: ${{ secrets.SSH_USER }}
-#          key: ${{ secrets.SSH_PRIVATE_KEY }}
-#          source: "target/*.jar"
-#          target: "/var/www/yourapp/app.jar"
-#
-#      - name: Restart Spring Boot App on Ubuntu VM
-#        uses: appleboy/ssh-action@v0.1.7
-#        with:
-#          host: ${{ secrets.SSH_HOST }}
-#          username: ${{ secrets.SSH_USER }}
-#          key: ${{ secrets.SSH_PRIVATE_KEY }}
-#          script: |
-#            pkill -f 'java' || true
-#            cd /var/www/yourapp
-#            nohup java -jar app.jar --spring.profiles.active=prod > app.log 2>&1 &
-#            echo "App deployed and running!"
+          host: ${{ secrets.VM_HOST }}
+          username: ${{ secrets.VM_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          envs: DB_URL,DB_USER,DB_PASS
+          script: |
+            export DB_URL=${{ secrets.DB_URL }}
+            export DB_USER=${{ secrets.DB_USER }}
+            export DB_PASS=${{ secrets.DB_PASS }}
+            
+            pkill -f 'java' || true
+            cd /home/${{ secrets.VM_USER }}/Goceng-prod/target
+            nohup java -jar *.jar --spring.profiles.active=prod > app.log 2>&1 &
+            sleep 10
+            curl --fail http://localhost:8080/actuator/health || (echo "App failed health check" && exit 1)
